### PR TITLE
Bootstrap Project

### PR DESCRIPTION
**Pull request by rootDEV2990**
Hi please help me review before i continue. Pull request to be closed after review as development is still ongoing. This pull request was created for review by TSE for inquiry of usage of foundation on bootstrap project. As per pathwrite no specifications were listed on not using foundation and its an alternative to the widely known bootstrap (which im trying to migrate from). Stickler and validator still pending as develpment is still underway. Thanks...any comments about my semantics are greatly appreciated too.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Comment by nikasulo** [comment]
# Great job so far! 
It's nice that you asked for some guidance, and I think it is a conversation better suited for Slack. Do you mind sending me a message when you see this?

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by rootDEV2990** [comment]
Activated Repo in SticklerCI. Will close and reopen pull request for changes to take effect.

**Comment by rootDEV2990** [comment]
Re-opening of pull request for SticklerCI to activate.

**Comment by rootDEV2990** [comment]
Re-opening of pull request for SticklerCI to activate.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### You have done great and for also implementing changes from previous reviews. Congratulation :boom: :100: You project has been approved.
### You can merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
